# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidthAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdata',
            name='input',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='routerdata',
            name='interface',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='routerdata',
            name='output',
            field=models.IntegerField(null=True),
        ),
    ]
